package GUI;

import Model.Schedule;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.*;
import java.util.Locale;

public class DeleteSchedule extends JDialog {
    private JPanel contentPane;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JTextField textField1;
    private JPanel buttonPanel;
    private JPanel infoContainer;
    private JPanel inputPanel;
    private JLabel prompt;
    private JButton fetchInfoButton;
    private JLabel status;
    private JLabel Warning;
    private JLabel room;
    private JLabel slot;
    private JLabel teacher;
    private JLabel Name;
    Schedule schedule = new Schedule();

    public DeleteSchedule() {
        Styling.styleButton(buttonOK, "#DC2626", "#B91C1C");
        Styling.styleButton(buttonCancel, "#738599", "#6A7584");
        Styling.styleButton(fetchInfoButton, "#2563EB", "#1D4ED8");
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);

        buttonOK.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOK();
            }
        });

        buttonCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        });

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        fetchInfoButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                schedule.fetchDeleteScheduleInfo(textField1, teacher, room, slot, Warning, status);
            }
        });
    }

    private void onOK() {
        if (textField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill All the required Fields!");
            return;
        }
        schedule.deleteSchedule(textField1);
        dispose();
    }

    private void onCancel() {
        // add your code here if necessary
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setBackground(new Color(-920071));
        contentPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        infoContainer = new JPanel();
        infoContainer.setLayout(new BorderLayout(0, 0));
        infoContainer.setBackground(new Color(-1));
        contentPane.add(infoContainer, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(480, -1), null, 0, false));
        infoContainer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), "Delete A Schedule", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, 20, infoContainer.getFont()), new Color(-14800581)));
        inputPanel = new JPanel();
        inputPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        inputPanel.setBackground(new Color(-1));
        infoContainer.add(inputPanel, BorderLayout.NORTH);
        inputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        prompt = new JLabel();
        prompt.setForeground(new Color(-10193781));
        prompt.setHorizontalAlignment(2);
        prompt.setHorizontalTextPosition(2);
        prompt.setText("Enter Schedule ID:");
        inputPanel.add(prompt);
        textField1 = new JTextField();
        textField1.setBackground(new Color(-1));
        textField1.setForeground(new Color(-10193781));
        textField1.setPreferredSize(new Dimension(180, 34));
        inputPanel.add(textField1);
        fetchInfoButton = new JButton();
        fetchInfoButton.setBackground(new Color(-12877066));
        fetchInfoButton.setBorderPainted(false);
        fetchInfoButton.setFocusPainted(false);
        fetchInfoButton.setFocusable(true);
        fetchInfoButton.setForeground(new Color(-1));
        fetchInfoButton.setPreferredSize(new Dimension(100, 34));
        fetchInfoButton.setText("Fetch info");
        inputPanel.add(fetchInfoButton);
        status = new JLabel();
        status.setForeground(new Color(-1));
        status.setText("[Status]");
        inputPanel.add(status);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-1));
        panel1.setPreferredSize(new Dimension(590, 90));
        infoContainer.add(panel1, BorderLayout.WEST);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        Warning = new JLabel();
        Font WarningFont = this.$$$getFont$$$(null, Font.BOLD, 14, Warning.getFont());
        if (WarningFont != null) Warning.setFont(WarningFont);
        Warning.setForeground(new Color(-10193781));
        Warning.setText("Are you sure you want to delete Schedule? This Action can not be undone...");
        panel1.add(Warning, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        room = new JLabel();
        Font roomFont = this.$$$getFont$$$(null, Font.BOLD, 14, room.getFont());
        if (roomFont != null) room.setFont(roomFont);
        room.setForeground(new Color(-10193781));
        room.setText("Room:");
        panel1.add(room, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        slot = new JLabel();
        Font slotFont = this.$$$getFont$$$(null, Font.BOLD, 14, slot.getFont());
        if (slotFont != null) slot.setFont(slotFont);
        slot.setForeground(new Color(-10193781));
        slot.setText("Slot:");
        panel1.add(slot, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        teacher = new JLabel();
        Font teacherFont = this.$$$getFont$$$(null, Font.BOLD, 14, teacher.getFont());
        if (teacherFont != null) teacher.setFont(teacherFont);
        teacher.setForeground(new Color(-10193781));
        teacher.setText("Teacher:");
        panel1.add(teacher, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        buttonPanel.setBackground(new Color(-920071));
        contentPane.add(buttonPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        buttonPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        panel2.setBackground(new Color(-920071));
        buttonPanel.add(panel2);
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        buttonOK = new JButton();
        buttonOK.setBackground(new Color(-1096636));
        buttonOK.setBorderPainted(false);
        buttonOK.setFocusPainted(false);
        buttonOK.setForeground(new Color(-1));
        buttonOK.setText("Delete");
        panel2.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonCancel = new JButton();
        buttonCancel.setBackground(new Color(-7363656));
        buttonCancel.setBorderPainted(false);
        buttonCancel.setFocusPainted(false);
        buttonCancel.setForeground(new Color(-1));
        buttonCancel.setText("Cancel");
        panel2.add(buttonCancel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
